# Generated by Django 4.2.6 on 2023-10-30 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
        ('Professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='Department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.department'),
        ),
        migrations.AddField(
            model_name='officehours',
            name='Professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Professor.professor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Professor.professor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.student'),
        ),
    ]
