# Generated by Django 4.2.6 on 2023-10-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officehours',
            options={'ordering': ['Professor', 'Day'], 'verbose_name_plural': 'Office Hours'},
        ),
        migrations.AddField(
            model_name='professor',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
