# Generated by Django 4.2.6 on 2023-10-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0003_alter_officehours_options_professor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Day',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
