# Generated by Django 4.2.6 on 2023-11-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0005_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['Professor', 'Day', 'Date', 'Time'], 'verbose_name_plural': 'Appointments'},
        ),
    ]
