# Generated by Django 4.2.6 on 2023-11-02 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0006_alter_appointment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='officehours',
            name='Office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_hours', to='Professor.professor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Professor.professor'),
        ),
    ]
