# Generated by Django 4.2.6 on 2023-11-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0009_alter_officehours_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officehours',
            name='Day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday')], max_length=3),
        ),
    ]
