# Generated by Django 4.2.6 on 2023-11-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0010_alter_officehours_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officehours',
            name='Day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=3),
        ),
    ]
