# Generated by Django 4.2.6 on 2023-10-30 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Department_Code', models.CharField(max_length=5)),
                ('Department_Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'ordering': ['Department_Code'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('First_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('Department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.department')),
            ],
            options={
                'verbose_name_plural': 'Students',
                'ordering': ['Last_Name'],
            },
        ),
    ]
